// 1 africa
// 2 america
// 3 asia
// 4 atlantic
// 5 australia
// 6 brazil
// 7 canada
// 8 chile
// 9 europe
// 10 indian
// 11 mexico
// 12 pacific
// 13 antarctica
// 14 etc

module.exports = {
  '0': [
    '14/utc',
    '1/abidjan',
    '1/accra',
    '1/bamako',
    '1/banjul',
    '1/bissau',
    '1/conakry',
    '1/dakar',
    '1/freetown',
    '1/lome',
    '1/monrovia',
    '1/nouakchott',
    '1/ouagadougou',
    '1/sao_tome',
    '1/timbuktu',
    '2/danmarkshavn',
    '4/reykjavik',
    '4/st_helena',
    '14/gmt',
    '14/gmt+0',
    '14/gmt-0',
    '14/gmt0',
    '14/greenwich',
    '14/universal',
    '14/zulu'
  ],
  '1': [
    '1/lagos',
    '1/algiers',
    '1/bangui',
    '1/brazzaville',
    '1/douala',
    '1/kinshasa',
    '1/libreville',
    '1/luanda',
    '1/malabo',
    '1/ndjamena',
    '1/niamey',
    '1/porto-novo',
    '1/tunis'
  ],
  '2': [
    '1/johannesburg',
    '1/blantyre',
    '1/bujumbura',
    '1/cairo',
    '1/gaborone',
    '1/harare',
    '1/khartoum',
    '1/kigali',
    '1/lubumbashi',
    '1/lusaka',
    '1/maputo',
    '1/maseru',
    '1/mbabane',
    '1/tripoli',
    '9/kaliningrad'
  ],
  '3': [
    '9/istanbul',
    '1/addis_ababa',
    '1/asmara',
    '1/asmera',
    '1/dar_es_salaam',
    '1/djibouti',
    '1/juba',
    '1/kampala',
    '1/mogadishu',
    '1/nairobi',
    '13/syowa',
    '3/aden',
    '3/baghdad',
    '3/bahrain',
    '3/istanbul',
    '3/kuwait',
    '3/qatar',
    '3/riyadh',
    '9/kirov',
    '9/minsk',
    '9/moscow',
    '9/simferopol',
    '9/volgograd',
    '10/antananarivo',
    '10/comoro',
    '10/mayotte'
  ],
  '4': [
    '3/dubai',
    '3/muscat',
    '3/tbilisi',
    '3/yerevan',
    '9/astrakhan',
    '9/samara',
    '9/saratov',
    '9/ulyanovsk',
    '10/mahe',
    '10/mauritius',
    '10/reunion'
  ],
  '5': [
    '3/karachi',
    '13/mawson',
    '3/aqtau',
    '3/aqtobe',
    '3/ashgabat',
    '3/ashkhabad',
    '3/atyrau',
    '3/baku',
    '3/dushanbe',
    '3/oral',
    '3/samarkand',
    '3/tashkent',
    '3/yekaterinburg',
    '10/kerguelen',
    '10/maldives'
  ],
  '6': [
    '3/dhaka',
    '13/vostok',
    '3/almaty',
    '3/bishkek',
    '3/dacca',
    '3/kashgar',
    '3/omsk',
    '3/qyzylorda',
    '3/thimbu',
    '3/thimphu',
    '3/urumqi',
    '10/chagos'
  ],
  '7': [
    '3/jakarta',
    '13/davis',
    '3/bangkok',
    '3/barnaul',
    '3/ho_chi_minh',
    '3/hovd',
    '3/krasnoyarsk',
    '3/novokuznetsk',
    '3/novosibirsk',
    '3/phnom_penh',
    '3/pontianak',
    '3/saigon',
    '3/vientiane',
    '10/christmas'
  ],
  '8': [
    '3/shanghai',
    '13/casey',
    '3/brunei',
    '3/choibalsan',
    '3/chongqing',
    '3/chungking',
    '3/harbin',
    '3/hong_kong',
    '3/irkutsk',
    '3/kuala_lumpur',
    '3/kuching',
    '3/macao',
    '3/macau',
    '3/makassar',
    '3/manila',
    '3/singapore',
    '3/taipei',
    '3/ujung_pandang',
    '3/ulaanbaatar',
    '5/perth',
    '5/west'
  ],
  '9': [
    '3/tokyo',
    '3/chita',
    '3/dili',
    '3/jayapura',
    '3/khandyga',
    '3/pyongyang',
    '3/seoul',
    '12/palau'
  ],
  '10': [
    '5/brisbane',
    '13/dumontdurville',
    '3/ust-nera',
    '3/vladivostok',
    '3/yakutsk',
    '5/lindeman',
    '5/queensland',
    '12/chuuk',
    '12/guam',
    '12/port_moresby',
    '12/saipan',
    '12/truk',
    '12/yap'
  ],
  '11': [
    '12/bougainville',
    '13/macquarie',
    '3/magadan',
    '3/sakhalin',
    '12/efate',
    '12/guadalcanal',
    '12/kosrae',
    '12/noumea',
    '12/pohnpei',
    '12/ponape'
  ],
  '12': [
    '3/anadyr',
    '3/kamchatka',
    '3/srednekolymsk',
    '12/funafuti',
    '12/kwajalein',
    '12/majuro',
    '12/nauru',
    '12/tarawa',
    '12/wake',
    '12/wallis'
  ],
  '13': ['12/enderbury', '12/fakaofo'],
  '14': ['12/kiritimati'],
  '-1': ['4/cape_verde'],
  '-10': ['12/honolulu', '12/johnston', '12/rarotonga', '12/tahiti'],
  '-11': ['12/midway', '12/niue', '12/pago_pago', '12/samoa'],
  '-2': ['2/noronha', '4/south_georgia', '6/denoronha'],
  '-2.5|dst': ['2/st_johns', '7/newfoundland'],
  '-2|dst': ['2/godthab', '2/miquelon'],
  '-3': [
    '2/buenos_aires',
    '2/araguaina',
    '2/argentina',
    '2/bahia',
    '2/belem',
    '2/catamarca',
    '2/cayenne',
    '2/cordoba',
    '2/fortaleza',
    '2/jujuy',
    '2/maceio',
    '2/mendoza',
    '2/montevideo',
    '2/paramaribo',
    '2/punta_arenas',
    '2/recife',
    '2/rosario',
    '2/santarem',
    '13/rothera',
    '4/stanley'
  ],
  '-3|dst': [
    '2/halifax',
    '2/glace_bay',
    '2/goose_bay',
    '2/moncton',
    '2/sao_paulo',
    '2/thule',
    '7/4',
    '4/bermuda',
    '6/east'
  ],
  '-4': [
    '6/west',
    '2/anguilla',
    '2/antigua',
    '2/aruba',
    '2/barbados',
    '2/blanc-sablon',
    '2/boa_vista',
    '2/caracas',
    '2/curacao',
    '2/dominica',
    '2/grenada',
    '2/guadeloupe',
    '2/guyana',
    '2/kralendijk',
    '2/la_paz',
    '2/lower_princes',
    '2/manaus',
    '2/marigot',
    '2/martinique',
    '2/montserrat',
    '2/port_of_spain',
    '2/porto_velho',
    '2/puerto_rico',
    '2/santo_domingo',
    '2/st_barthelemy',
    '2/st_kitts',
    '2/st_lucia',
    '2/st_thomas',
    '2/st_vincent',
    '2/tortola',
    '2/virgin'
  ],
  '-4|dst': [
    '2/new_york',
    '2/asuncion',
    '2/campo_grande',
    '2/cuiaba',
    '2/detroit',
    '2/fort_wayne',
    '2/grand_turk',
    '2/havana',
    '2/10a',
    '2/10apolis',
    '2/iqaluit',
    '2/kentucky',
    '2/louisville',
    '2/montreal',
    '2/nassau',
    '2/nipigon',
    '2/pangnirtung',
    '2/port-au-prince',
    '2/santiago',
    '2/thunder_bay',
    '2/toronto',
    '7/eastern',
    '8/continental',
    '13/palmer'
  ],
  '-5': [
    '2/lima',
    '2/atikokan',
    '2/bogota',
    '2/cancun',
    '2/cayman',
    '2/coral_harbour',
    '2/eirunepe',
    '2/guayaquil',
    '2/jamaica',
    '2/panama',
    '2/porto_acre',
    '2/rio_branco',
    '6/acre'
  ],
  '-5|dst': [
    '2/chicago',
    '2/bahia_banderas',
    '2/knox_in',
    '2/matamoros',
    '2/menominee',
    '2/merida',
    '2/11_city',
    '2/monterrey',
    '2/north_dakota',
    '2/rainy_river',
    '2/rankin_inlet',
    '2/resolute',
    '2/winnipeg',
    '7/central',
    '11/general'
  ],
  '-6': [
    '2/belize',
    '2/costa_rica',
    '2/el_salvador',
    '2/guatemala',
    '2/managua',
    '2/regina',
    '2/swift_current',
    '2/tegucigalpa',
    '7/east-saskatchewan',
    '7/saskatchewan',
    '12/galapagos'
  ],
  '-6|dst': [
    '2/denver',
    '2/boise',
    '2/cambridge_bay',
    '2/chihuahua',
    '2/edmonton',
    '2/inuvik',
    '2/mazatlan',
    '2/ojinaga',
    '2/shiprock',
    '2/yellowknife',
    '7/mountain',
    '8/easterisland',
    '11/bajasur',
    '12/easter'
  ],
  '-7': ['2/dawson_creek', '2/creston', '2/hermosillo', '2/phoenix'],
  '-7|dst': [
    '2/los_angeles',
    '2/dawson',
    '2/ensenada',
    '2/santa_isabel',
    '2/tijuana',
    '2/vancouver',
    '2/whitehorse',
    '7/12',
    '7/yukon',
    '11/bajanorte'
  ],
  '-8': ['12/pitcairn'],
  '-8|dst': ['2/anchorage', '2/juneau', '2/metlakatla', '2/nome', '2/sitka', '2/yakutat'],
  '-9': ['12/gambier'],
  '-9.5': ['12/marquesas'],
  '-9|dst': ['2/adak', '2/atka'],
  '0|dst': ['2/scoresbysund', '4/azores'],
  '10.5|dst': ['5/lord_howe', '5/lhi'],
  '10|dst': [
    '5/sydney',
    '5/act',
    '5/canberra',
    '5/currie',
    '5/hobart',
    '5/melbourne',
    '5/nsw',
    '5/tasmania',
    '5/victoria'
  ],
  '11.5': ['12/norfolk'],
  '12.75|dst': ['12/chatham'],
  '12|dst': ['12/auckland', '12/fiji', '13/mcmurdo', '13/south_pole'],
  '13|dst': ['12/apia', '12/tongatapu'],
  '1|dst': [
    '9/london',
    '9/belfast',
    '9/dublin',
    '9/guernsey',
    '9/isle_of_man',
    '9/jersey',
    '9/lisbon',
    '4/canary',
    '4/faeroe',
    '4/faroe',
    '4/madeira',
    '1/casablanca',
    '1/el_aaiun',
    '1/windhoek'
  ],
  '2|dst': [
    '9/paris',
    '9/amsterdam',
    '9/andorra',
    '9/belgrade',
    '9/berlin',
    '9/bratislava',
    '9/brussels',
    '9/budapest',
    '9/busingen',
    '9/copenhagen',
    '9/gibraltar',
    '9/ljubljana',
    '9/luxembourg',
    '9/madrid',
    '9/malta',
    '9/monaco',
    '9/oslo',
    '9/podgorica',
    '9/prague',
    '9/rome',
    '9/san_marino',
    '9/sarajevo',
    '9/skopje',
    '9/stockholm',
    '9/tirane',
    '9/vaduz',
    '9/vatican',
    '9/vienna',
    '9/warsaw',
    '9/zagreb',
    '9/zurich',
    'arctic/longyearbyen',
    '13/troll',
    '4/jan_mayen',
    '1/ceuta'
  ],
  '3|dst': [
    '9/athens',
    '9/bucharest',
    '9/chisinau',
    '9/helsinki',
    '9/kiev',
    '9/mariehamn',
    '9/nicosia',
    '9/riga',
    '9/sofia',
    '9/tallinn',
    '9/tiraspol',
    '9/uzhgorod',
    '9/vilnius',
    '9/zaporozhye',
    '3/amman',
    '3/beirut',
    '3/damascus',
    '3/gaza',
    '3/hebron',
    '3/jerusalem',
    '3/nicosia',
    '3/tel_aviv'
  ],
  '4.5': ['3/kabul'],
  '4.5|dst': ['3/tehran'],
  '5.5': ['3/calcutta', '3/colombo', '3/kolkata'],
  '5.75': ['3/kathmandu', '3/katmandu'],
  '6.5': ['3/rangoon', '10/cocos'],
  '8.75': ['5/eucla'],
  '8|dst': ['3/ulan_bator'],
  '9.5': ['5/darwin', '5/north'],
  '9.5|dst': ['5/adelaide', '5/broken_hill', '5/south', '5/yancowinna']
}
