export default {
  AS: ['Pacific/Pago_Pago'],
  NU: ['Pacific/Niue'],
  UM: ['Pacific/Midway', 'Pacific/Wake'],
  CK: ['Pacific/Rarotonga'],
  PF: ['Pacific/Tahiti', 'Pacific/Marquesas', 'Pacific/Gambier'],
  US: [
    'Pacific/Honolulu',
    'America/Adak',
    'America/Anchorage',
    'America/Juneau',
    'America/Sitka',
    'America/Metlakatla',
    'America/Yakutat',
    'America/Nome',
    'America/Los_Angeles',
    'America/Phoenix',
    'America/Denver',
    'America/Boise',
    'America/Chicago',
    'America/Indiana/Tell_City',
    'America/Indiana/Knox',
    'America/Menominee',
    'America/North_Dakota/Center',
    'America/North_Dakota/New_Salem',
    'America/North_Dakota/Beulah',
    'America/New_York',
    'America/Detroit',
    'America/Kentucky/Louisville',
    'America/Kentucky/Monticello',
    'America/Indiana/Indianapolis',
    'America/Indiana/Vincennes',
    'America/Indiana/Winamac',
    'America/Indiana/Marengo',
    'America/Indiana/Petersburg',
    'America/Indiana/Vevay'
  ],
  PN: ['Pacific/Pitcairn'],
  CA: [
    'America/Vancouver',
    'America/Creston',
    'America/Dawson_Creek',
    'America/Fort_Nelson',
    'America/Whitehorse',
    'America/Dawson',
    'America/Edmonton',
    'America/Cambridge_Bay',
    'America/Yellowknife',
    'America/Inuvik',
    'America/Regina',
    'America/Swift_Current',
    'America/Winnipeg',
    'America/Rainy_River',
    'America/Resolute',
    'America/Rankin_Inlet',
    'America/Atikokan',
    'America/Toronto',
    'America/Nipigon',
    'America/Thunder_Bay',
    'America/Iqaluit',
    'America/Pangnirtung',
    'America/Blanc-Sablon',
    'America/Halifax',
    'America/Glace_Bay',
    'America/Moncton',
    'America/Goose_Bay',
    'America/St_Johns'
  ],
  MX: [
    'America/Tijuana',
    'America/Hermosillo',
    'America/Mazatlan',
    'America/Chihuahua',
    'America/Ojinaga',
    'America/Mexico_City',
    'America/Merida',
    'America/Monterrey',
    'America/Matamoros',
    'America/Bahia_Banderas',
    'America/Cancun'
  ],
  BZ: ['America/Belize'],
  CR: ['America/Costa_Rica'],
  EC: ['Pacific/Galapagos', 'America/Guayaquil'],
  GT: ['America/Guatemala'],
  HN: ['America/Tegucigalpa'],
  NI: ['America/Managua'],
  SV: ['America/El_Salvador'],
  CL: ['Pacific/Easter', 'America/Santiago', 'America/Punta_Arenas'],
  BR: [
    'America/Eirunepe',
    'America/Rio_Branco',
    'America/Campo_Grande',
    'America/Cuiaba',
    'America/Porto_Velho',
    'America/Boa_Vista',
    'America/Manaus',
    'America/Belem',
    'America/Fortaleza',
    'America/Recife',
    'America/Araguaina',
    'America/Maceio',
    'America/Bahia',
    'America/Sao_Paulo',
    'America/Santarem',
    'America/Noronha'
  ],
  CO: ['America/Bogota'],
  JM: ['America/Jamaica'],
  KY: ['America/Cayman'],
  PA: ['America/Panama'],
  PE: ['America/Lima'],
  BS: ['America/Nassau'],
  CU: ['America/Havana'],
  HT: ['America/Port-au-Prince'],
  TC: ['America/Grand_Turk'],
  AG: ['America/Antigua'],
  AI: ['America/Anguilla'],
  AW: ['America/Aruba'],
  BB: ['America/Barbados'],
  BL: ['America/St_Barthelemy'],
  BO: ['America/La_Paz'],
  BQ: ['America/Kralendijk'],
  CW: ['America/Curacao'],
  DM: ['America/Dominica'],
  DO: ['America/Santo_Domingo'],
  GD: ['America/Grenada'],
  GP: ['America/Guadeloupe'],
  GY: ['America/Guyana'],
  KN: ['America/St_Kitts'],
  LC: ['America/St_Lucia'],
  MF: ['America/Marigot'],
  MQ: ['America/Martinique'],
  MS: ['America/Montserrat'],
  PR: ['America/Puerto_Rico'],
  SX: ['America/Lower_Princes'],
  TT: ['America/Port_of_Spain'],
  VC: ['America/St_Vincent'],
  VE: ['America/Caracas'],
  VG: ['America/Tortola'],
  VI: ['America/St_Thomas'],
  BM: ['Atlantic/Bermuda'],
  GL: ['America/Thule', 'America/Nuuk', 'America/Scoresbysund', 'America/Danmarkshavn'],
  PY: ['America/Asuncion'],
  AQ: [
    'Antarctica/Palmer',
    'Antarctica/Rothera',
    'Antarctica/Troll',
    'Antarctica/Syowa',
    'Antarctica/Mawson',
    'Antarctica/Vostok',
    'Antarctica/Davis',
    'Antarctica/DumontDUrville',
    'Antarctica/Casey',
    'Antarctica/McMurdo'
  ],
  AR: [
    'America/Argentina/Buenos_Aires',
    'America/Argentina/Cordoba',
    'America/Argentina/Salta',
    'America/Argentina/Jujuy',
    'America/Argentina/Tucuman',
    'America/Argentina/Catamarca',
    'America/Argentina/La_Rioja',
    'America/Argentina/San_Juan',
    'America/Argentina/Mendoza',
    'America/Argentina/San_Luis',
    'America/Argentina/Rio_Gallegos',
    'America/Argentina/Ushuaia'
  ],
  FK: ['Atlantic/Stanley'],
  GF: ['America/Cayenne'],
  SR: ['America/Paramaribo'],
  UY: ['America/Montevideo'],
  PM: ['America/Miquelon'],
  GS: ['Atlantic/South_Georgia'],
  CV: ['Atlantic/Cape_Verde'],
  PT: ['Atlantic/Azores', 'Europe/Lisbon', 'Atlantic/Madeira'],
  BF: ['Africa/Ouagadougou'],
  CI: ['Africa/Abidjan'],
  GH: ['Africa/Accra'],
  GM: ['Africa/Banjul'],
  GN: ['Africa/Conakry'],
  GW: ['Africa/Bissau'],
  IS: ['Atlantic/Reykjavik'],
  LR: ['Africa/Monrovia'],
  ML: ['Africa/Bamako'],
  MR: ['Africa/Nouakchott'],
  SH: ['Atlantic/St_Helena'],
  SL: ['Africa/Freetown'],
  SN: ['Africa/Dakar'],
  ST: ['Africa/Sao_Tome'],
  TG: ['Africa/Lome'],
  ES: ['Atlantic/Canary', 'Europe/Madrid', 'Africa/Ceuta'],
  FO: ['Atlantic/Faroe'],
  GB: ['Europe/London'],
  GG: ['Europe/Guernsey'],
  IM: ['Europe/Isle_of_Man'],
  JE: ['Europe/Jersey'],
  AO: ['Africa/Luanda'],
  BJ: ['Africa/Porto-Novo'],
  CD: ['Africa/Kinshasa', 'Africa/Lubumbashi'],
  CF: ['Africa/Bangui'],
  CG: ['Africa/Brazzaville'],
  CM: ['Africa/Douala'],
  DZ: ['Africa/Algiers'],
  EH: ['Africa/El_Aaiun'],
  GA: ['Africa/Libreville'],
  GQ: ['Africa/Malabo'],
  IE: ['Europe/Dublin'],
  MA: ['Africa/Casablanca'],
  NE: ['Africa/Niamey'],
  NG: ['Africa/Lagos'],
  TD: ['Africa/Ndjamena'],
  TN: ['Africa/Tunis'],
  AD: ['Europe/Andorra'],
  AL: ['Europe/Tirane'],
  AT: ['Europe/Vienna'],
  BA: ['Europe/Sarajevo'],
  BE: ['Europe/Brussels'],
  CH: ['Europe/Zurich'],
  CZ: ['Europe/Prague'],
  DE: ['Europe/Berlin', 'Europe/Busingen'],
  DK: ['Europe/Copenhagen'],
  FR: ['Europe/Paris'],
  GI: ['Europe/Gibraltar'],
  HR: ['Europe/Zagreb'],
  HU: ['Europe/Budapest'],
  IT: ['Europe/Rome'],
  LI: ['Europe/Vaduz'],
  LU: ['Europe/Luxembourg'],
  MC: ['Europe/Monaco'],
  ME: ['Europe/Podgorica'],
  MK: ['Europe/Skopje'],
  MT: ['Europe/Malta'],
  NL: ['Europe/Amsterdam'],
  NO: ['Europe/Oslo'],
  PL: ['Europe/Warsaw'],
  RS: ['Europe/Belgrade'],
  SE: ['Europe/Stockholm'],
  SI: ['Europe/Ljubljana'],
  SJ: ['Arctic/Longyearbyen'],
  SK: ['Europe/Bratislava'],
  SM: ['Europe/San_Marino'],
  VA: ['Europe/Vatican'],
  BI: ['Africa/Bujumbura'],
  BW: ['Africa/Gaborone'],
  EG: ['Africa/Cairo'],
  LS: ['Africa/Maseru'],
  LY: ['Africa/Tripoli'],
  MW: ['Africa/Blantyre'],
  MZ: ['Africa/Maputo'],
  NA: ['Africa/Windhoek'],
  RU: [
    'Europe/Kaliningrad',
    'Europe/Moscow',
    'Europe/Kirov',
    'Europe/Volgograd',
    'Europe/Astrakhan',
    'Europe/Saratov',
    'Europe/Ulyanovsk',
    'Europe/Samara',
    'Asia/Yekaterinburg',
    'Asia/Omsk',
    'Asia/Novosibirsk',
    'Asia/Barnaul',
    'Asia/Tomsk',
    'Asia/Novokuznetsk',
    'Asia/Krasnoyarsk',
    'Asia/Irkutsk',
    'Asia/Chita',
    'Asia/Yakutsk',
    'Asia/Khandyga',
    'Asia/Vladivostok',
    'Asia/Ust-Nera',
    'Asia/Magadan',
    'Asia/Sakhalin',
    'Asia/Srednekolymsk',
    'Asia/Kamchatka',
    'Asia/Anadyr'
  ],
  RW: ['Africa/Kigali'],
  SD: ['Africa/Khartoum'],
  SZ: ['Africa/Mbabane'],
  ZA: ['Africa/Johannesburg'],
  ZM: ['Africa/Lusaka'],
  ZW: ['Africa/Harare'],
  AX: ['Europe/Mariehamn'],
  BG: ['Europe/Sofia'],
  CY: ['Asia/Nicosia', 'Asia/Famagusta'],
  EE: ['Europe/Tallinn'],
  FI: ['Europe/Helsinki'],
  GR: ['Europe/Athens'],
  IL: ['Asia/Jerusalem'],
  JO: ['Asia/Amman'],
  LB: ['Asia/Beirut'],
  LT: ['Europe/Vilnius'],
  LV: ['Europe/Riga'],
  MD: ['Europe/Chisinau'],
  PS: ['Asia/Gaza', 'Asia/Hebron'],
  RO: ['Europe/Bucharest'],
  SS: ['Africa/Juba'],
  SY: ['Asia/Damascus'],
  UA: ['Europe/Kiev', 'Europe/Uzhgorod', 'Europe/Zaporozhye', 'Europe/Simferopol'],
  BH: ['Asia/Bahrain'],
  BY: ['Europe/Minsk'],
  DJ: ['Africa/Djibouti'],
  ER: ['Africa/Asmara'],
  ET: ['Africa/Addis_Ababa'],
  IQ: ['Asia/Baghdad'],
  KE: ['Africa/Nairobi'],
  KM: ['Indian/Comoro'],
  KW: ['Asia/Kuwait'],
  MG: ['Indian/Antananarivo'],
  QA: ['Asia/Qatar'],
  SA: ['Asia/Riyadh'],
  SO: ['Africa/Mogadishu'],
  TR: ['Europe/Istanbul'],
  TZ: ['Africa/Dar_es_Salaam'],
  UG: ['Africa/Kampala'],
  YE: ['Asia/Aden'],
  YT: ['Indian/Mayotte'],
  IR: ['Asia/Tehran'],
  AE: ['Asia/Dubai'],
  AM: ['Asia/Yerevan'],
  AZ: ['Asia/Baku'],
  GE: ['Asia/Tbilisi'],
  MU: ['Indian/Mauritius'],
  OM: ['Asia/Muscat'],
  RE: ['Indian/Reunion'],
  SC: ['Indian/Mahe'],
  AF: ['Asia/Kabul'],
  KZ: [
    'Asia/Qyzylorda',
    'Asia/Aqtobe',
    'Asia/Aqtau',
    'Asia/Atyrau',
    'Asia/Oral',
    'Asia/Almaty',
    'Asia/Qostanay'
  ],
  MV: ['Indian/Maldives'],
  PK: ['Asia/Karachi'],
  TF: ['Indian/Kerguelen'],
  TJ: ['Asia/Dushanbe'],
  TM: ['Asia/Ashgabat'],
  UZ: ['Asia/Samarkand', 'Asia/Tashkent'],
  IN: ['Asia/Kolkata'],
  LK: ['Asia/Colombo'],
  NP: ['Asia/Kathmandu'],
  BD: ['Asia/Dhaka'],
  BT: ['Asia/Thimphu'],
  CN: ['Asia/Urumqi', 'Asia/Shanghai'],
  IO: ['Indian/Chagos'],
  KG: ['Asia/Bishkek'],
  CC: ['Indian/Cocos'],
  MM: ['Asia/Yangon'],
  CX: ['Indian/Christmas'],
  ID: ['Asia/Jakarta', 'Asia/Pontianak', 'Asia/Makassar', 'Asia/Jayapura'],
  KH: ['Asia/Phnom_Penh'],
  LA: ['Asia/Vientiane'],
  MN: ['Asia/Hovd', 'Asia/Ulaanbaatar', 'Asia/Choibalsan'],
  TH: ['Asia/Bangkok'],
  VN: ['Asia/Ho_Chi_Minh'],
  AU: [
    'Australia/Perth',
    'Australia/Eucla',
    'Australia/Darwin',
    'Australia/Broken_Hill',
    'Australia/Adelaide',
    'Australia/Brisbane',
    'Australia/Lindeman',
    'Antarctica/Macquarie',
    'Australia/Hobart',
    'Australia/Melbourne',
    'Australia/Sydney',
    'Australia/Lord_Howe'
  ],
  BN: ['Asia/Brunei'],
  HK: ['Asia/Hong_Kong'],
  MO: ['Asia/Macau'],
  MY: ['Asia/Kuala_Lumpur', 'Asia/Kuching'],
  PH: ['Asia/Manila'],
  SG: ['Asia/Singapore'],
  TW: ['Asia/Taipei'],
  JP: ['Asia/Tokyo'],
  KP: ['Asia/Pyongyang'],
  KR: ['Asia/Seoul'],
  PW: ['Pacific/Palau'],
  TL: ['Asia/Dili'],
  FM: ['Pacific/Chuuk', 'Pacific/Pohnpei', 'Pacific/Kosrae'],
  GU: ['Pacific/Guam'],
  MP: ['Pacific/Saipan'],
  PG: ['Pacific/Port_Moresby', 'Pacific/Bougainville'],
  NC: ['Pacific/Noumea'],
  SB: ['Pacific/Guadalcanal'],
  VU: ['Pacific/Efate'],
  NF: ['Pacific/Norfolk'],
  KI: ['Pacific/Tarawa', 'Pacific/Enderbury', 'Pacific/Kiritimati'],
  MH: ['Pacific/Majuro', 'Pacific/Kwajalein'],
  NR: ['Pacific/Nauru'],
  TV: ['Pacific/Funafuti'],
  WF: ['Pacific/Wallis'],
  FJ: ['Pacific/Fiji'],
  NZ: ['Pacific/Auckland', 'Pacific/Chatham'],
  TK: ['Pacific/Fakaofo'],
  TO: ['Pacific/Tongatapu'],
  WS: ['Pacific/Apia']
}
