/* eslint-disable no-console */
import fs from 'node:fs'
import { pack } from 'efrt'
import { validateData } from './lib/validate-data.js'

import zones from '../data/index.js'

validateData()

const packed = {}
Object.keys(zones).forEach(k => {
  const arr = k.split(/\//)
  const top = arr[0]
  const name = arr.slice(1).join('/')
  packed[top] = packed[top] || {}
  const { dst, names, meta, hem } = Object.assign({}, zones[k])
  packed[top][name] = [pack(names), meta, hem]
  if (dst) {
    packed[top][name].push(dst)
  }
})

//write it to a file in ./src
const outFile = new URL('../src/generated/zones.js', import.meta.url)
fs.mkdirSync(new URL('../src/generated/', import.meta.url), { recursive: true })
fs.writeFileSync(outFile, '// Generated by scripts/pack.js. Edit data/ instead.\nexport default ' + JSON.stringify(packed) + '\n', 'utf8')

//get filesize
const stats = fs.statSync(outFile)
const size = (stats['size'] / 1000.0).toFixed(1)

console.log('       - packed into  ' + size + 'k\n')
