import fs from 'node:fs'
// avoid requiring our whole package.json file
// make a small file for our version number
const pkg = JSON.parse(fs.readFileSync(new URL('../package.json', import.meta.url), 'utf8'))

fs.mkdirSync(new URL('../src/generated/', import.meta.url), { recursive: true })
fs.writeFileSync(new URL('../src/generated/version.js', import.meta.url), `// Generated by scripts/version.js.\nexport default '${pkg.version}'\n`)
