// strings that don't pack properly
export default {
  'gmt+0': 'Etc/GMT',
  'gmt-0': 'Etc/GMT',
  gmt0: 'Etc/GMT',
  'etc/gmt+0': 'Etc/GMT',
  'etc/gmt-0': 'Etc/GMT',
  'etc/gmt0': 'Etc/GMT',
  'msk+00': 'Europe/Moscow',
  'msk-01 - kaliningrad': 'Europe/Kaliningrad',
  'msk+00 - moscow area': 'Europe/Moscow',
  'msk+00 - crimea': 'Europe/Kiev',
  'msk+00 - volgograd': 'Europe/Volgograd',
  'msk+00 - kirov': 'Europe/Kirov',
  'msk+01 - astrakhan': 'Europe/Astrakhan',
  'msk+01 - saratov': 'Europe/Saratov',
  'msk+01 - ulyanovsk': 'Europe/Ulyanovsk',
  'msk+01 - samaraudmurtia': 'Europe/Samara',
  'msk+02 - urals': 'Asia/Yekaterinburg',
  'msk+03': 'Asia/Omsk',
  'msk+04 - novosibirsk': 'Asia/Novosibirsk',
  'msk+04 - altai': 'Asia/Barnaul',
  'msk+04': 'Asia/Tomsk',
  'msk+04 - kemerovo': 'Asia/Novokuznetsk',
  'msk+04 - krasnoyarsk area': 'Asia/Krasnoyarsk',
  'msk+05 - irkutskburyatia': 'Asia/Irkutsk',
  'msk+06 - zabaykalsky': 'Asia/Chita',
  'msk+06 - lena river': 'Asia/Yakutsk',
  'msk+06 - tomponskyust-maysky': 'Asia/Khandyga',
  'msk+07 - amur river': 'Asia/Vladivostok',
  'msk+07 - oymyakonsky': 'Asia/Ust-Nera',
  'msk+08 - magadan': 'Asia/Magadan',
  'msk+08 - sakhalin island': 'Asia/Sakhalin',
  'msk+08 - sakha (e) north kuril is': 'Asia/Srednekolymsk',
  'msk+09': 'Asia/Kamchatka',
  'msk+09 - bering sea': 'Asia/Anadyr',
  "russia time zone 11": "Asia/Anadyr",
  "russia time zone 10": "Asia/Srednekolymsk",
  "russia time zone 3": "Europe/Samara",
  "coordinated universal time-09": "Pacific/Gambier",
  "utc-09": "Pacific/Gambier",
  "coordinated universal time-08": "Pacific/Pitcairn"
}
